# -*- coding: utf-8 -*-
"""inpaint2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XqZVhGH0Bk2_Egbgnz0PV6NUyZIobkoX
"""

import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread("/content/sample1.png")
mask = cv2.imread("/content/sample2.png")
inpaintRadius = int(input("enter the inpaint radius "))
mask = cv2.cvtColor(mask,cv2.COLOR_BGR2GRAY)

dim = image.shape
dim=(dim[1],dim[0])
image = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)
mask = cv2.resize(mask, dim, interpolation = cv2.INTER_AREA)

cv2_imshow(image)
cv2_imshow(mask)

output = cv2.inpaint(image, mask, inpaintRadius, cv2.INPAINT_TELEA)
cv2_imshow(output)